# copy and paste here from Decapbridge
# Use DecapBridge auth (required)
backend:
    name: git-gateway
    repo: BuckyBuck135/Intermediate-Website-Kit-SASS
    branch: main
    identity_url: https://auth.decapbridge.com/sites/5c0227b5-f331-433a-bd30-f3ce7d78464c
    gateway_url: https://gateway.decapbridge.com

    # Quickly see who did what (optional)
    commit_messages:
        create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
        update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
        delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
        uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
        deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
        openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://testing-sass-kit.netlify.app

# Keep this to allow you to edit the cms locally
local_backend: true

# Image folders
media_folder: "src/assets/images/blog"
public_folder: "/assets/images/blog"

# Decap CMS Collections
collections:
    - name: "blog"
      label: "Blog"
      folder: "src/content/blog"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
                label: "URL Slug",
                name: "url",
                widget: "string",
                hint: 'Specify where the page will be written to. If you use "Blog Post", the post will be accessible from "blog/blog-post"',
            }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
          - { label: "Featured Image", name: "image", widget: "image" }
          - { label: "Image Caption", name: "imageAlt", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
